### PR TITLE
Support count queries with joins

### PR DESCRIPTION
**Pull request by machty**
In our app, we have more complex scopes with joins + distinct_on that cause something like the following error when you call `.count` on it. This PR fixes this, and also runs against actual Postgres rather than SQLite to more proactively surface issues like these in the future.

```
ERROR:  column \"customers.id\" must appear in the GROUP BY clause or be used in an aggregate function
```

### CODE REVIEW

**Comment by alecdotninja** [comment]
Thank you for looking into this and adding tests! I will review this shortly and cut a new release.

**Comment by machty** [comment]
This has been working well for us on production for a few months now -- any chance we could this merged?

**Comment by alecdotninja** [comment]
Thanks for the bump. I totally forgot about this PR.

**Comment by alecdotninja** [comment]
@machty Thank you for your work on this! This is now released as [v1.5.0](https://rubygems.org/gems/active_record_distinct_on/versions/1.5.0).

**Pull request merged**
