### PR TITLE
Add support for Rails 7.1

### LINKED ISSUE #27: Add support for Rails 7.1
See: https://github.com/alecdotninja/active_record_distinct_on/blob/9e0f0a6ead19d96caa0e2ab08248b15f724deb60/active_record_distinct_on.gemspec#L20

```
Could not find compatible versions

Because active_record_distinct_on >= 1.5.0 depends on activerecord >= 5.2, < 7.1
  and rails >= 7.1.0 depends on activerecord = 7.1.0,
  active_record_distinct_on >= 1.5.0 is incompatible with rails >= 7.1.0.
So, because Gemfile depends on rails ~> 7.1
  and Gemfile depends on active_record_distinct_on ~> 1.5.0,
  version solving has failed.
```

### PR DESCRIPTION
**Pull request by ezekg**
Closes #27. Also drops support for Rails 5.2 and 6.0, which [are EOL](https://endoflife.date/rails).

### CODE REVIEW

**Comment by ezekg** [comment]
Updated appraisals to reflect supported Rails versions.

**Comment by ezekg** [comment]
@alecdotninja would you have a second to rerun the workflow and review?

Also — consider applying for [GitHub Sponsors](https://github.com/sponsors). Would love to sponsor this gem on behalf of my company, @keygen-sh. We use it and would love to contribute, both monetarily and more, to ensure that it's well maintained into the future. 🙂

**Comment by michael-cybrid** [comment]
@alecdotninja , would it be possible to get this released? With 7.1 out now, this would be very helpful.

**Comment by ezekg** [comment]
@alecdotninja can we sponsor you so we can get this moved forward?

**Comment by ezekg** [comment]
Any update here?

**Comment by ezekg** [comment]
@alecdotninja any update here?

**Comment by alecdotninja** [comment]
@ezekg @michael-cybrid I'm sorry for the delay here. This is now released in [v1.6](https://rubygems.org/gems/active_record_distinct_on/versions/1.6.0).

@ezekg Thanks for sending that email. The signal to noise ratio of Github emails for me is really low right now, so it easy for stuff to get missed. I'll follow up with you there.

**Pull request merged**
