### PR TITLE
Fix arel_attribute deprecation

### PR DESCRIPTION
**Pull request by yosiat**
Error:
```
ActiveSupport::DeprecationException:
  DEPRECATION WARNING: arel_attribute is deprecated and will be removed from Rails 6.2
./vendor/bundle/ruby/2.7.0/gems/active_record_distinct_on-1.1.0/lib/active_record_distinct_on/distinct_on_query_methods.rb:35:in `block in distinct_on!'
./vendor/bundle/ruby/2.7.0/gems/active_record_distinct_on-1.1.0/lib/active_record_distinct_on/distinct_on_query_methods.rb:31:in `map!'
./vendor/bundle/ruby/2.7.0/gems/active_record_distinct_on-1.1.0/lib/active_record_distinct_on/distinct_on_query_methods.rb:31:in `distinct_on!'
./vendor/bundle/ruby/2.7.0/gems/active_record_distinct_on-1.1.0/lib/active_record_distinct_on/distinct_on_query_methods.rb:26:in `distinct_on'
```

arel_attribute is going to be deprecated (see: https://github.com/rails/rails/pull/39881), using arel_table instead.

### CODE REVIEW

**Comment by yosiat** [comment]
@alecdotninja can you please give it a look?

**Comment by alecdotninja** [comment]
Thanks for your work on this, @yosiat . I'm sorry to keep you waiting.

I would merge, but it looks like CI for this project is not actually running. I'll pull everything down and verify it this weekend. :smile:

**Comment by yosiat** [comment]
@alecdotninja if you want, I can do a PR for setting-up a CI using Github Actions (I created one for panko, and it's simple - https://github.com/panko-serializer/panko_serializer/blob/master/.github/workflows/ruby.yml)

**Comment by alecdotninja** [comment]
Thank you for getting this fixed, @yosiat ! This is now released in [v1.2.0](https://rubygems.org/gems/active_record_distinct_on/versions/1.2.0). :tada:

**Pull request merged**
