### PR TITLE
Gem will work on `4.2.1`

### PR DESCRIPTION
**Pull request by kuldeepaggarwal**
Tested on Rails-4.2.1 version in my current project and everything is working fine.

### CODE REVIEW

**Comment by alecdotninja** [comment]
Thanks for the PR, @kuldeepaggarwal! Would you try removing the `activesupport` dependency to see if that clears up the security warning?

Since `activesupport` is a dependency of `activerecord` anyway, I don't think there is an issue with removing it.

**Comment by kuldeepaggarwal** [comment]
Sure!!

**Comment by kuldeepaggarwal** [comment]
@anarchocurious Updated the PR

**Comment by kuldeepaggarwal** [comment]
Can you please release a new version so that I can refer to my project's Gemfile?

**Comment by alecdotninja** [comment]
I just pushed it out as `v0.1.2`. Thanks for your contribution!

**Pull request merged**
